title: While loop with a Boolean in Python
hero_image: images/banner.png
description: Learn how to create a while loop with a Boolean variable
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games, jokes/pranks, music/sound, photography, physical computing, robots, space"
technologies: "electronics, sense-hat, physical computing, html/css, scratch, python"
site_areas:
steps:
  - title: Introduction
